# Generated by Django 3.0.8 on 2020-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200727_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
    ]
